window.TARGET_LANGUAGE_TRANSLATIONS = {
  en: {
    "American English": "American English",
    "British English": "British English",
    "Australian English": "Australian English",
    "Spanish — LATAM (Neutral)": "Spanish — LATAM (Neutral)",
    "Spanish — Mexican": "Spanish — Mexican",
    "Spanish — Central American": "Spanish — Central American",
    "Spanish — Caribbean": "Spanish — Caribbean",
    "Spanish — Peruvian": "Spanish — Peruvian",
    "Spanish — Argentine": "Spanish — Argentine",
    "Spanish — Chilean": "Spanish — Chilean",
    "Spanish — General Colombian": "Spanish — General Colombian",
    "Spanish — Venezuelan": "Spanish — Venezuelan",
    "Colombian Spanish — Paisa (Medellín)": "Colombian Spanish — Paisa (Medellín)",
    "Colombian Spanish — Rolo (Bogotá)": "Colombian Spanish — Rolo (Bogotá)",
    "Colombian Spanish — Cali": "Colombian Spanish — Cali",
    "Colombian Spanish — Santander": "Colombian Spanish — Santander",
    "French": "French",
    "German": "German",
    "Italian": "Italian",
    "Brazilian Portuguese": "Brazilian Portuguese",
    "European Portuguese": "European Portuguese",
    "Modern Standard Arabic": "Modern Standard Arabic",
    "Egyptian Arabic": "Egyptian Arabic",
    "Iranian Persian — Farsi": "Iranian Persian — Farsi",
    "Afghan Persian — Dari": "Afghan Persian — Dari",
    "Tajik Persian — Tajik": "Tajik Persian — Tajik",
    "Hindi": "Hindi",
    "Indonesian": "Indonesian",
    "Filipino (Tagalog)": "Filipino (Tagalog)",
    "Swahili": "Swahili",
    "Amharic": "Amharic",
    "Turkish": "Turkish",
    "Mandarin Chinese": "Mandarin Chinese",
    "Korean": "Korean",
    "Japanese": "Japanese",
    "Russian": "Russian"
  },
  es: {
    "American English": "Inglés estadounidense",
    "British English": "Inglés británico",
    "Australian English": "Inglés australiano",
    "Spanish — LATAM (Neutral)": "Español latinoamericano (neutral)",
    "Spanish — Mexican": "Español mexicano",
    "Spanish — Central American": "Español centroamericano",
    "Spanish — Caribbean": "Español caribeño",
    "Spanish — Peruvian": "Español peruano",
    "Spanish — Argentine": "Español argentino",
    "Spanish — Chilean": "Español chileno",
    "Spanish — General Colombian": "Español colombiano general",
    "Spanish — Venezuelan": "Español venezolano",
    "Colombian Spanish — Paisa (Medellín)": "Español colombiano — Paisa (Medellín)",
    "Colombian Spanish — Rolo (Bogotá)": "Español colombiano — Rolo (Bogotá)",
    "Colombian Spanish — Cali": "Español colombiano — Cali",
    "Colombian Spanish — Santander": "Español colombiano — Santander",
    "French": "Francés",
    "German": "Alemán",
    "Italian": "Italiano",
    "Brazilian Portuguese": "Portugués brasileño",
    "European Portuguese": "Portugués europeo",
    "Modern Standard Arabic": "Árabe estándar moderno",
    "Egyptian Arabic": "Árabe egipcio",
    "Iranian Persian — Farsi": "Persa iraní — Farsi",
    "Afghan Persian — Dari": "Persa afgano — Dari",
    "Tajik Persian — Tajik": "Persa tayiko — Tayiko",
    "Hindi": "Hindi",
    "Indonesian": "Indonesio",
    "Filipino (Tagalog)": "Filipino (Tagalo)",
    "Swahili": "Suajili",
    "Amharic": "Amhárico",
    "Turkish": "Turco",
    "Mandarin Chinese": "Chino mandarín",
    "Korean": "Coreano",
    "Japanese": "Japonés",
    "Russian": "Ruso"
  }
};

window.languageCatalog = [
  { label: "American English", aliases: ["english", "american", "us", "usa", "united states"], popularity: 90 },
  { label: "British English", aliases: ["british", "brit", "uk", "england", "queen's english", "cheers", "mate", "colour", "favour"], popularity: 70 },
  { label: "Australian English", aliases: ["australian", "aussie", "australia", "gday", "g'day", "mate"], popularity: 65 },

  { label: "Spanish — LATAM (Neutral)", aliases: ["spanish", "espanol", "español", "latam", "latin american", "neutral spanish"], popularity: 100 },
  { label: "Spanish — Mexican", aliases: ["mexican", "mexico", "méxico"], popularity: 80 },
  { label: "Spanish — Central American", aliases: ["central american", "central america", "centroamericano"], popularity: 50 },
  { label: "Spanish — Caribbean", aliases: ["caribbean", "caribe", "caribeño"], popularity: 55 },
  { label: "Spanish — Peruvian", aliases: ["peruvian", "peru", "perú"], popularity: 45 },
  { label: "Spanish — Argentine", aliases: ["argentine", "argentina", "vos", "che"], popularity: 60 },
  { label: "Spanish — Chilean", aliases: ["chilean", "chile", "chileno"], popularity: 45 },
  { label: "Spanish — General Colombian", aliases: ["colombian", "colombia", "col"], dialectGroup: "colombian", popularity: 85 },
  { label: "Spanish — Venezuelan", aliases: ["venezuelan", "venezuela", "venez"], popularity: 55 },

  { label: "Colombian Spanish — Paisa (Medellín)", aliases: ["paisa", "pais", "medellin", "medellín", "parce", "parcero", "que mas", "qué más", "pa"], dialectGroup: "colombian", popularity: 84 },
  { label: "Colombian Spanish — Rolo (Bogotá)", aliases: ["rolo", "bogota", "bogotá", "sumercé", "sumerce"], dialectGroup: "colombian", popularity: 78 },
  { label: "Colombian Spanish — Cali", aliases: ["cali", "caleño", "caleno"], dialectGroup: "colombian", popularity: 60 },
  { label: "Colombian Spanish — Santander", aliases: ["santander", "santandereano"], dialectGroup: "colombian", popularity: 55 },

  { label: "French", aliases: ["france", "francais", "français"], popularity: 70 },
  { label: "German", aliases: ["deutsch", "germany"], popularity: 65 },
  { label: "Italian", aliases: ["italy", "italiano"], popularity: 65 },
  { label: "Brazilian Portuguese", aliases: ["brazil", "brasil", "portuguese", "português"], popularity: 75 },
  { label: "European Portuguese", aliases: ["portugal"], popularity: 55 },
  { label: "Modern Standard Arabic", aliases: ["arabic", "msa"], popularity: 70 },
  { label: "Egyptian Arabic", aliases: ["egyptian", "egypt"], popularity: 55 },
  { label: "Iranian Persian — Farsi", aliases: ["farsi", "persian", "iranian"], popularity: 55 },
  { label: "Afghan Persian — Dari", aliases: ["dari", "afghan"], popularity: 40 },
  { label: "Tajik Persian — Tajik", aliases: ["tajik"], popularity: 35 },
  { label: "Hindi", aliases: ["india"], popularity: 65 },
  { label: "Indonesian", aliases: ["indonesia"], popularity: 55 },
  { label: "Filipino (Tagalog)", aliases: ["filipino", "tagalog", "philippines"], popularity: 55 },
  { label: "Swahili", aliases: [], popularity: 40 },
  { label: "Amharic", aliases: [], popularity: 35 },
  { label: "Turkish", aliases: ["turkey"], popularity: 55 },
  { label: "Mandarin Chinese", aliases: ["chinese", "mandarin", "china"], popularity: 70 },
  { label: "Korean", aliases: ["korea"], popularity: 60 },
  { label: "Japanese", aliases: ["japan"], popularity: 60 },
  { label: "Russian", aliases: ["russia"], popularity: 60 }
];
