window.TARGET_LANGUAGE_TRANSLATIONS = {
  "en": {
    "American English": "American English",
    "British English": "British English",
    "Australian English": "Australian English",
    "Spanish — LATAM (Neutral)": "Spanish — LATAM (Neutral)",
    "Spanish — Mexican": "Spanish — Mexican",
    "Spanish — Central American": "Spanish — Central American",
    "Spanish — Caribbean": "Spanish — Caribbean",
    "Spanish — Peruvian": "Spanish — Peruvian",
    "Spanish — Argentine": "Spanish — Argentine",
    "Spanish — Chilean": "Spanish — Chilean",
    "Spanish — General Colombian": "Spanish — General Colombian",
    "Spanish — Venezuelan": "Spanish — Venezuelan",
    "Colombian Spanish — Paisa (Medellín)": "Colombian Spanish — Paisa (Medellín)",
    "Colombian Spanish — Rolo (Bogotá)": "Colombian Spanish — Rolo (Bogotá)",
    "Colombian Spanish — Cali": "Colombian Spanish — Cali",
    "Colombian Spanish — Santander": "Colombian Spanish — Santander",
    "French": "French",
    "Occitan (Southern France)": "Occitan (Southern France)",
    "German": "German",
    "Italian": "Italian",
    "Brazilian Portuguese": "Brazilian Portuguese",
    "European Portuguese": "European Portuguese",
    "Modern Standard Arabic": "Modern Standard Arabic",
    "Egyptian Arabic": "Egyptian Arabic",
    "Iranian Persian — Farsi": "Iranian Persian — Farsi",
    "Afghan Persian — Dari": "Afghan Persian — Dari",
    "Tajik Persian — Tajik": "Tajik Persian — Tajik",
    "Hindi": "Hindi",
    "Indonesian": "Indonesian",
    "Filipino (Tagalog)": "Filipino (Tagalog)",
    "Swahili": "Swahili",
    "Amharic": "Amharic",
    "Turkish": "Turkish",
    "Mandarin Chinese": "Mandarin Chinese",
    "Korean": "Korean",
    "Japanese": "Japanese",
    "Russian": "Russian"
  },
  "es": {
    "American English": "Inglés estadounidense",
    "British English": "Inglés británico",
    "Australian English": "Inglés australiano",
    "Spanish — LATAM (Neutral)": "Español latinoamericano (neutral)",
    "Spanish — Mexican": "Español mexicano",
    "Spanish — Central American": "Español centroamericano",
    "Spanish — Caribbean": "Español caribeño",
    "Spanish — Peruvian": "Español peruano",
    "Spanish — Argentine": "Español argentino",
    "Spanish — Chilean": "Español chileno",
    "Spanish — General Colombian": "Español colombiano general",
    "Spanish — Venezuelan": "Español venezolano",
    "Colombian Spanish — Paisa (Medellín)": "Español colombiano — Paisa (Medellín)",
    "Colombian Spanish — Rolo (Bogotá)": "Español colombiano — Rolo (Bogotá)",
    "Colombian Spanish — Cali": "Español colombiano — Cali",
    "Colombian Spanish — Santander": "Español colombiano — Santander",
    "French": "Francés",
    "Occitan (Southern France)": "Occitano (sur de Francia)",
    "German": "Alemán",
    "Italian": "Italiano",
    "Brazilian Portuguese": "Portugués brasileño",
    "European Portuguese": "Portugués europeo",
    "Modern Standard Arabic": "Árabe estándar moderno",
    "Egyptian Arabic": "Árabe egipcio",
    "Iranian Persian — Farsi": "Persa iraní — Farsi",
    "Afghan Persian — Dari": "Persa afgano — Dari",
    "Tajik Persian — Tajik": "Persa tayiko — Tayiko",
    "Hindi": "Hindi",
    "Indonesian": "Indonesio",
    "Filipino (Tagalog)": "Filipino (Tagalo)",
    "Swahili": "Suajili",
    "Amharic": "Amhárico",
    "Turkish": "Turco",
    "Mandarin Chinese": "Chino mandarín",
    "Korean": "Coreano",
    "Japanese": "Japonés",
    "Russian": "Ruso"
  },
  "fr": {
    "American English": "Anglais américain",
    "British English": "Anglais britannique",
    "Australian English": "Anglais australien",
    "Spanish — LATAM (Neutral)": "Espagnol latino-américain (neutre)",
    "Spanish — Mexican": "Espagnol mexicain",
    "Spanish — Central American": "Espagnol d’Amérique centrale",
    "Spanish — Caribbean": "Espagnol caribéen",
    "Spanish — Peruvian": "Espagnol péruvien",
    "Spanish — Argentine": "Espagnol argentin",
    "Spanish — Chilean": "Espagnol chilien",
    "Spanish — General Colombian": "Espagnol colombien général",
    "Spanish — Venezuelan": "Espagnol vénézuélien",
    "Colombian Spanish — Paisa (Medellín)": "Espagnol colombien — Paisa (Medellín)",
    "Colombian Spanish — Rolo (Bogotá)": "Espagnol colombien — Rolo (Bogotá)",
    "Colombian Spanish — Cali": "Espagnol colombien — Cali",
    "Colombian Spanish — Santander": "Espagnol colombien — Santander",
    "French": "Français",
    "Occitan (Southern France)": "Occitan (sud de la France)",
    "German": "Allemand",
    "Italian": "Italien",
    "Brazilian Portuguese": "Portugais brésilien",
    "European Portuguese": "Portugais européen",
    "Modern Standard Arabic": "Arabe standard moderne",
    "Egyptian Arabic": "Arabe égyptien",
    "Iranian Persian — Farsi": "Persan iranien — farsi",
    "Afghan Persian — Dari": "Persan afghan — dari",
    "Tajik Persian — Tajik": "Persan tadjik — tadjik",
    "Hindi": "Hindi",
    "Indonesian": "Indonésien",
    "Filipino (Tagalog)": "Philippin (tagalog)",
    "Swahili": "Swahili",
    "Amharic": "Amharique",
    "Turkish": "Turc",
    "Mandarin Chinese": "Chinois mandarin",
    "Korean": "Coréen",
    "Japanese": "Japonais",
    "Russian": "Russe"
  },
  "de": {
    "American English": "Amerikanisches Englisch",
    "British English": "Britisches Englisch",
    "Australian English": "Australisches Englisch",
    "Spanish — LATAM (Neutral)": "Lateinamerikanisches Spanisch (neutral)",
    "Spanish — Mexican": "Mexikanisches Spanisch",
    "Spanish — Central American": "Zentralamerikanisches Spanisch",
    "Spanish — Caribbean": "Karibisches Spanisch",
    "Spanish — Peruvian": "Peruanisches Spanisch",
    "Spanish — Argentine": "Argentinisches Spanisch",
    "Spanish — Chilean": "Chilenisches Spanisch",
    "Spanish — General Colombian": "Allgemeines kolumbianisches Spanisch",
    "Spanish — Venezuelan": "Venezolanisches Spanisch",
    "Colombian Spanish — Paisa (Medellín)": "Kolumbianisches Spanisch — Paisa (Medellín)",
    "Colombian Spanish — Rolo (Bogotá)": "Kolumbianisches Spanisch — Rolo (Bogotá)",
    "Colombian Spanish — Cali": "Kolumbianisches Spanisch — Cali",
    "Colombian Spanish — Santander": "Kolumbianisches Spanisch — Santander",
    "French": "Französisch",
    "Occitan (Southern France)": "Okzitanisch (Südfrankreich)",
    "German": "Deutsch",
    "Italian": "Italienisch",
    "Brazilian Portuguese": "Brasilianisches Portugiesisch",
    "European Portuguese": "Europäisches Portugiesisch",
    "Modern Standard Arabic": "Modernes Hocharabisch",
    "Egyptian Arabic": "Ägyptisches Arabisch",
    "Iranian Persian — Farsi": "Iranisches Persisch — Farsi",
    "Afghan Persian — Dari": "Afghanisches Persisch — Dari",
    "Tajik Persian — Tajik": "Tadschikisches Persisch — Tadschikisch",
    "Hindi": "Hindi",
    "Indonesian": "Indonesisch",
    "Filipino (Tagalog)": "Filipino (Tagalog)",
    "Swahili": "Suaheli",
    "Amharic": "Amharisch",
    "Turkish": "Türkisch",
    "Mandarin Chinese": "Mandarin-Chinesisch",
    "Korean": "Koreanisch",
    "Japanese": "Japanisch",
    "Russian": "Russisch"
  },
  "pt-BR": {
    "American English": "Inglês americano",
    "British English": "Inglês britânico",
    "Australian English": "Inglês australiano",
    "Spanish — LATAM (Neutral)": "Espanhol latino-americano (neutro)",
    "Spanish — Mexican": "Espanhol mexicano",
    "Spanish — Central American": "Espanhol centro-americano",
    "Spanish — Caribbean": "Espanhol caribenho",
    "Spanish — Peruvian": "Espanhol peruano",
    "Spanish — Argentine": "Espanhol argentino",
    "Spanish — Chilean": "Espanhol chileno",
    "Spanish — General Colombian": "Espanhol colombiano geral",
    "Spanish — Venezuelan": "Espanhol venezuelano",
    "Colombian Spanish — Paisa (Medellín)": "Espanhol colombiano — Paisa (Medellín)",
    "Colombian Spanish — Rolo (Bogotá)": "Espanhol colombiano — Rolo (Bogotá)",
    "Colombian Spanish — Cali": "Espanhol colombiano — Cali",
    "Colombian Spanish — Santander": "Espanhol colombiano — Santander",
    "French": "Francês",
    "Occitan (Southern France)": "Occitano (sul da França)",
    "German": "Alemão",
    "Italian": "Italiano",
    "Brazilian Portuguese": "Português brasileiro",
    "European Portuguese": "Português europeu",
    "Modern Standard Arabic": "Árabe padrão moderno",
    "Egyptian Arabic": "Árabe egípcio",
    "Iranian Persian — Farsi": "Persa iraniano — farsi",
    "Afghan Persian — Dari": "Persa afegão — dari",
    "Tajik Persian — Tajik": "Persa tajique — tajique",
    "Hindi": "Hindi",
    "Indonesian": "Indonésio",
    "Filipino (Tagalog)": "Filipino (tagalo)",
    "Swahili": "Suaíli",
    "Amharic": "Amárico",
    "Turkish": "Turco",
    "Mandarin Chinese": "Chinês mandarim",
    "Korean": "Coreano",
    "Japanese": "Japonês",
    "Russian": "Russo"
  }
};

window.languageCatalog = [
  { label: "American English", aliases: ["english", "american", "us", "usa", "united states"], popularity: 90 },
  { label: "British English", aliases: ["british", "brit", "uk", "england", "queen's english", "cheers", "mate", "colour", "favour"], popularity: 70 },
  { label: "Australian English", aliases: ["australian", "aussie", "australia", "gday", "g'day", "mate"], popularity: 65 },

  { label: "Spanish — LATAM (Neutral)", aliases: ["spanish", "espanol", "español", "latam", "latin american", "neutral spanish"], popularity: 100 },
  { label: "Spanish — Mexican", aliases: ["mexican", "mexico", "méxico"], popularity: 80 },
  { label: "Spanish — Central American", aliases: ["central american", "central america", "centroamericano"], popularity: 50 },
  { label: "Spanish — Caribbean", aliases: ["caribbean", "caribe", "caribeño"], popularity: 55 },
  { label: "Spanish — Peruvian", aliases: ["peruvian", "peru", "perú"], popularity: 45 },
  { label: "Spanish — Argentine", aliases: ["argentine", "argentina", "vos", "che"], popularity: 60 },
  { label: "Spanish — Chilean", aliases: ["chilean", "chile", "chileno"], popularity: 45 },
  { label: "Spanish — General Colombian", aliases: ["colombian", "colombia", "col"], dialectGroup: "colombian", popularity: 85 },
  { label: "Spanish — Venezuelan", aliases: ["venezuelan", "venezuela", "venez"], popularity: 55 },

  { label: "Colombian Spanish — Paisa (Medellín)", aliases: ["paisa", "pais", "medellin", "medellín", "parce", "parcero", "que mas", "qué más", "pa"], dialectGroup: "colombian", popularity: 84 },
  { label: "Colombian Spanish — Rolo (Bogotá)", aliases: ["rolo", "bogota", "bogotá", "sumercé", "sumerce"], dialectGroup: "colombian", popularity: 78 },
  { label: "Colombian Spanish — Cali", aliases: ["cali", "caleño", "caleno"], dialectGroup: "colombian", popularity: 60 },
  { label: "Colombian Spanish — Santander", aliases: ["santander", "santandereano"], dialectGroup: "colombian", popularity: 55 },

  { label: "French", aliases: ["france", "francais", "français"], popularity: 70 },
  { label: "Occitan (Southern France)", aliases: ["occitan", "occitanie", "southern france", "southwest france", "southwestern france", "lenga d'oc", "langue d'oc", "provençal", "provencal"], popularity: 35 },
  { label: "German", aliases: ["deutsch", "germany"], popularity: 65 },
  { label: "Italian", aliases: ["italy", "italiano"], popularity: 65 },
  { label: "Brazilian Portuguese", aliases: ["brazil", "brasil", "portuguese", "português"], popularity: 75 },
  { label: "European Portuguese", aliases: ["portugal"], popularity: 55 },
  { label: "Modern Standard Arabic", aliases: ["arabic", "msa"], popularity: 70 },
  { label: "Egyptian Arabic", aliases: ["egyptian", "egypt"], popularity: 55 },
  { label: "Iranian Persian — Farsi", aliases: ["farsi", "persian", "iranian"], popularity: 55 },
  { label: "Afghan Persian — Dari", aliases: ["dari", "afghan"], popularity: 40 },
  { label: "Tajik Persian — Tajik", aliases: ["tajik"], popularity: 35 },
  { label: "Hindi", aliases: ["india"], popularity: 65 },
  { label: "Indonesian", aliases: ["indonesia"], popularity: 55 },
  { label: "Filipino (Tagalog)", aliases: ["filipino", "tagalog", "philippines"], popularity: 55 },
  { label: "Swahili", aliases: [], popularity: 40 },
  { label: "Amharic", aliases: [], popularity: 35 },
  { label: "Turkish", aliases: ["turkey"], popularity: 55 },
  { label: "Mandarin Chinese", aliases: ["chinese", "mandarin", "china"], popularity: 70 },
  { label: "Korean", aliases: ["korea"], popularity: 60 },
  { label: "Japanese", aliases: ["japan"], popularity: 60 },
  { label: "Russian", aliases: ["russia"], popularity: 60 }
];
