const TARGET_LANGUAGE_TRANSLATIONS = {
  en: {
    "American English": "American English",
    "British English": "British English",
    "Australian English": "Australian English",
    "French": "French",
    "German": "German",
    "Italian": "Italian",
    "Spanish — LATAM (Neutral)": "Spanish — LATAM (Neutral)",
    "Spanish — Mexican": "Spanish — Mexican",
    "Spanish — Central American": "Spanish — Central American",
    "Spanish — Caribbean": "Spanish — Caribbean",
    "Spanish — Peruvian": "Spanish — Peruvian",
    "Spanish — Argentine": "Spanish — Argentine",
    "Spanish — Chilean": "Spanish — Chilean",
    "Spanish — General Colombian": "Spanish — General Colombian",
    "Spanish — Venezuelan": "Spanish — Venezuelan",
    "Colombian Spanish — Paisa (Medellín)": "Colombian Spanish — Paisa (Medellín)",
    "Colombian Spanish — Rolo (Bogotá)": "Colombian Spanish — Rolo (Bogotá)",
    "Colombian Spanish — Cali": "Colombian Spanish — Cali",
    "Colombian Spanish — Santander": "Colombian Spanish — Santander",
    "Brazilian Portuguese": "Brazilian Portuguese",
    "European Portuguese": "European Portuguese",
    "Modern Standard Arabic": "Modern Standard Arabic",
    "Egyptian Arabic": "Egyptian Arabic",
    "Iranian Persian — Farsi": "Iranian Persian — Farsi",
    "Afghan Persian — Dari": "Afghan Persian — Dari",
    "Tajik Persian — Tajik": "Tajik Persian — Tajik",
    "Hindi": "Hindi",
    "Indonesian": "Indonesian",
    "Filipino (Tagalog)": "Filipino (Tagalog)",
    "Swahili": "Swahili",
    "Amharic": "Amharic",
    "Turkish": "Turkish",
    "Mandarin Chinese": "Mandarin Chinese",
    "Korean": "Korean",
    "Japanese": "Japanese",
    "Russian": "Russian"
  },
  es: {
    "American English": "Inglés estadounidense",
    "British English": "Inglés británico",
    "Australian English": "Inglés australiano",
    "French": "Francés",
    "German": "Alemán",
    "Italian": "Italiano",
    "Spanish — LATAM (Neutral)": "Español latinoamericano (neutral)",
    "Spanish — Mexican": "Español mexicano",
    "Spanish — Central American": "Español centroamericano",
    "Spanish — Caribbean": "Español caribeño",
    "Spanish — Peruvian": "Español peruano",
    "Spanish — Argentine": "Español argentino",
    "Spanish — Chilean": "Español chileno",
    "Spanish — General Colombian": "Español colombiano general",
    "Spanish — Venezuelan": "Español venezolano",
    "Colombian Spanish — Paisa (Medellín)": "Español colombiano — Paisa (Medellín)",
    "Colombian Spanish — Rolo (Bogotá)": "Español colombiano — Rolo (Bogotá)",
    "Colombian Spanish — Cali": "Español colombiano — Cali",
    "Colombian Spanish — Santander": "Español colombiano — Santander",
    "Brazilian Portuguese": "Portugués brasileño",
    "European Portuguese": "Portugués europeo",
    "Modern Standard Arabic": "Árabe estándar moderno",
    "Egyptian Arabic": "Árabe egipcio",
    "Iranian Persian — Farsi": "Persa iraní — Farsi",
    "Afghan Persian — Dari": "Persa afgano — Dari",
    "Tajik Persian — Tajik": "Persa tayiko — Tayiko",
    "Hindi": "Hindi",
    "Indonesian": "Indonesio",
    "Filipino (Tagalog)": "Filipino (Tagalo)",
    "Swahili": "Suajili",
    "Amharic": "Amhárico",
    "Turkish": "Turco",
    "Mandarin Chinese": "Chino mandarín",
    "Korean": "Coreano",
    "Japanese": "Japonés",
    "Russian": "Ruso"
  }
};

const languageCatalog = [
  { label: "American English", aliases: ["English", "English — American", "english", "en"] },
  { label: "British English", aliases: ["English — British", "british english"] },
  { label: "Australian English", aliases: ["English — Australian", "australian english"] },

  { label: "Spanish — LATAM (Neutral)", aliases: ["Spanish", "LATAM", "LATAM Spanish", "Latin American Spanish", "español", "espanol", "es"] },
  { label: "Spanish — Mexican", aliases: ["Mexican Spanish"] },
  { label: "Spanish — Central American", aliases: ["Central American Spanish"] },
  { label: "Spanish — Caribbean", aliases: ["Caribbean Spanish"] },
  { label: "Spanish — Peruvian", aliases: ["Peruvian Spanish"] },
  { label: "Spanish — Argentine", aliases: ["Argentine Spanish"] },
  { label: "Spanish — Chilean", aliases: ["Chilean Spanish"] },

  { label: "Spanish — General Colombian", aliases: ["General Colombian Spanish", "Colombian Spanish"] },
  { label: "Colombian Spanish — Paisa (Medellín)", aliases: ["Paisa", "Paisa Spanish", "Paisa Spanish (Medellín)", "Medellín Spanish"] },
  { label: "Colombian Spanish — Rolo (Bogotá)", aliases: ["Rolo", "Rolo Spanish", "Rolo Spanish (Bogotá)", "Bogotá Spanish"] },
  { label: "Colombian Spanish — Cali", aliases: ["Cali", "Cali Spanish"] },
  { label: "Colombian Spanish — Santander", aliases: ["Santander", "Santander Spanish"] },
  { label: "Spanish — Venezuelan", aliases: ["Venezuelan Spanish"] },

  { label: "French", aliases: ["français", "francais", "fr"] },
  { label: "German", aliases: ["deutsch", "de"] },
  { label: "Italian", aliases: ["italiano", "it"] },

  { label: "Brazilian Portuguese", aliases: ["Portuguese Brazil"] },
  { label: "European Portuguese", aliases: ["Portuguese Portugal"] },

  { label: "Modern Standard Arabic", aliases: ["Arabic", "MSA"] },
  { label: "Egyptian Arabic", aliases: [] },

  { label: "Iranian Persian — Farsi", aliases: ["Farsi", "Persian"] },
  { label: "Afghan Persian — Dari", aliases: ["Dari"] },
  { label: "Tajik Persian — Tajik", aliases: ["Tajik"] },

  { label: "Hindi", aliases: [] },
  { label: "Indonesian", aliases: [] },
  { label: "Filipino (Tagalog)", aliases: ["Tagalog", "Filipino"] },
  { label: "Swahili", aliases: [] },
  { label: "Amharic", aliases: [] },
  { label: "Turkish", aliases: [] },

  { label: "Mandarin Chinese", aliases: ["Chinese", "Mandarin"] },
  { label: "Korean", aliases: [] },
  { label: "Japanese", aliases: [] },
  { label: "Russian", aliases: [] }
];  { label: "Filipino (Tagalog)", aliases: ["tagalog"] },
  { label: "Swahili", aliases: [] },
  { label: "Amharic", aliases: [] },
  { label: "Turkish", aliases: [] },

  { label: "Mandarin Chinese", aliases: ["chinese"] },
  { label: "Korean", aliases: [] },
  { label: "Japanese", aliases: [] },
  { label: "Russian", aliases: [] }
];
