window.UI_TEXT = {
  en: {
    siteLanguage: "Site Language",
    title: "Cross-Cultural Translator™",
    subtitle: "Beyond translation — real cross-cultural communication",
    description: "Dialect-aware translation and cultural clarity",
    inputText: "Input Text",
    detected: "Detected language",
    confirmed: "Input language",
    keep: "Keep",
    change: "Change",
    dark: "🌙 Dark",
    light: "☀️ Light",
    changeInput: "Change input language to:",
    translateTo: "Translate To",
    translate: "Translate",
    translating: "Translating...",
    translation: "Translation",
    copy: "Copy",
    copied: "Copied",
    additionalInfo: "Additional Information",
    confirmInputFirst: "Confirm input language first",
    enterTextTarget: "Enter text and choose a language",
    serverTimeout: "Server is waking up or request timed out. Try again.",
    genericError: "Something went wrong. Please try again.",
    footer: "Built for real-world cross-cultural communication."
  },

  es: {
    siteLanguage: "Idioma del sitio",
    title: "Cross-Cultural Translator™",
    subtitle: "Más que traducción — comunicación intercultural real",
    description: "Traducción con sensibilidad dialectal y claridad cultural",
    inputText: "Texto de entrada",
    detected: "Idioma detectado",
    confirmed: "Idioma seleccionado",
    keep: "Mantener",
    change: "Cambiar",
    dark: "🌙 Oscuro",
    light: "☀️ Claro",
    changeInput: "Cambiar idioma de entrada a:",
    translateTo: "Traducir a",
    translate: "Traducir",
    translating: "Traduciendo...",
    translation: "Traducción",
    copy: "Copiar",
    copied: "Copiado",
    additionalInfo: "Información adicional",
    confirmInputFirst: "Confirma primero el idioma",
    enterTextTarget: "Escribe texto y elige idioma",
    serverTimeout: "El servidor está despertando o la solicitud tardó demasiado. Inténtalo otra vez.",
    genericError: "Algo salió mal. Inténtalo otra vez.",
    footer: "Creado para comunicación intercultural de la vida real."
  }
};
