window.UI_TEXT = {
  en: {
    siteLanguage: "Site Language",
    title: "Cross-Cultural Translator™",
    subtitle: "Beyond translation — real cross-cultural communication",
    description: "Dialect-aware translation and cultural clarity",
    inputText: "Input Text",
    detected: "Detected language",
    confirmed: "Input language",
    keep: "Keep",
    change: "Change",
    changeInput: "Change input language to:",
    translateTo: "Translate To",
    translate: "Translate",
    translating: "Translating...",
    translation: "Translation",
    copy: "Copy",
    copied: "Copied",
    additionalInfo: "Additional Information",
    confirmInputFirst: "Confirm input language first",
    enterTextTarget: "Enter text and choose a language",
    genericError: "Something went wrong. Please try again.",
    dark: "🌙 Dark",
    light: "☀️ Light",
    footer: "Cross-Cultural Translator™",
    audience: "Who are you talking to?",
    tone: "Tone / intent",
    goal: "Situation type",
    contextMode: "Communication mode",
    situation: "Extra context (optional)",
    situationPlaceholder: "Example: texting a friend, hotel front desk, romantic message, work email...",
    includeInfo: "Show cultural / tone notes when useful",
    simpleMode: "Simple",
    enhancedMode: "Enhanced Context",
    pronunciationToggleLabel: "Show Pronunciation",
    pronunciation: "Pronunciation",
    speakNormal: "Speak Normally",
    speakSlow: "Speak Slowly",
    typeMoreToDetect: "Type a little more to detect language",
    unsupportedPronunciation: "Pronunciation is not available for this language pair yet.",
    audienceOptions: {
      general: "General",
      friend: "Friend",
      romantic: "Romantic interest",
      professional: "Professional / boss",
      stranger: "Stranger",
      service: "Service employee"
    },
    toneOptions: {
      natural: "Natural and clear",
      casual: "Casual",
      formal: "Formal",
      respectful: "Respectful",
      playful: "Playful",
      urgent: "Urgent / direct"
    },
    goalOptions: {
      translate: "General translation",
      travel: "Travel / logistics",
      business: "Business / professional",
      social: "Social message",
      conflict: "Conflict / tension",
      flirting: "Flirting / chemistry"
    },
    contextModeOptions: {
      normal: "Normal",
      romantic: "Romantic / flirty",
      fictionalDialogue: "Fictional dialogue / novel",
      professional: "Professional",
      conflict: "Conflict / escalation"
    }
  },

  es: {
    siteLanguage: "Idioma del sitio",
    title: "Cross-Cultural Translator™",
    subtitle: "Más que traducción — comunicación intercultural real",
    description: "Traducción con sensibilidad dialectal y claridad cultural",
    inputText: "Texto de entrada",
    detected: "Idioma detectado",
    confirmed: "Idioma de entrada",
    keep: "Mantener",
    change: "Cambiar",
    changeInput: "Cambiar idioma de entrada a:",
    translateTo: "Traducir a",
    translate: "Traducir",
    translating: "Traduciendo...",
    translation: "Traducción",
    copy: "Copiar",
    copied: "Copiado",
    additionalInfo: "Información adicional",
    confirmInputFirst: "Confirma primero el idioma de entrada",
    enterTextTarget: "Escribe texto y elige un idioma",
    genericError: "Algo salió mal. Inténtalo de nuevo.",
    dark: "🌙 Oscuro",
    light: "☀️ Claro",
    footer: "Cross-Cultural Translator™",
    audience: "¿Con quién estás hablando?",
    tone: "Tono / intención",
    goal: "Tipo de situación",
    contextMode: "Modo de comunicación",
    situation: "Contexto extra (opcional)",
    situationPlaceholder: "Ejemplo: mensaje a un amigo, hotel, mensaje romántico, correo laboral...",
    includeInfo: "Mostrar notas culturales / de tono cuando sean útiles",
    simpleMode: "Simple",
    enhancedMode: "Contexto avanzado",
    pronunciationToggleLabel: "Mostrar pronunciación",
    pronunciation: "Pronunciación",
    speakNormal: "Hablar normal",
    speakSlow: "Hablar lento",
    typeMoreToDetect: "Escribe un poco más para detectar el idioma",
    unsupportedPronunciation: "La pronunciación todavía no está disponible para este par de idiomas.",
    audienceOptions: {
      general: "General",
      friend: "Amigo/a",
      romantic: "Interés romántico",
      professional: "Profesional / jefe",
      stranger: "Desconocido/a",
      service: "Empleado/a de servicio"
    },
    toneOptions: {
      natural: "Natural y claro",
      casual: "Casual",
      formal: "Formal",
      respectful: "Respetuoso",
      playful: "Juguetón",
      urgent: "Urgente / directo"
    },
    goalOptions: {
      translate: "Traducción general",
      travel: "Viaje / logística",
      business: "Negocios / profesional",
      social: "Mensaje social",
      conflict: "Conflicto / tensión",
      flirting: "Coqueteo / química"
    },
    contextModeOptions: {
      normal: "Normal",
      romantic: "Romántico / coqueto",
      fictionalDialogue: "Diálogo ficticio / novela",
      professional: "Profesional",
      conflict: "Conflicto / escalación"
    }
  },

  fr: {
    siteLanguage: "Langue du site",
    title: "Cross-Cultural Translator™",
    subtitle: "Au-delà de la traduction — une vraie communication interculturelle",
    description: "Traduction sensible aux dialectes et clarté culturelle",
    inputText: "Texte source",
    detected: "Langue détectée",
    confirmed: "Langue d’entrée",
    keep: "Garder",
    change: "Changer",
    changeInput: "Changer la langue d’entrée en :",
    translateTo: "Traduire vers",
    translate: "Traduire",
    translating: "Traduction...",
    translation: "Traduction",
    copy: "Copier",
    copied: "Copié",
    additionalInfo: "Informations supplémentaires",
    confirmInputFirst: "Confirmez d’abord la langue d’entrée",
    enterTextTarget: "Saisissez le texte et choisissez une langue",
    genericError: "Une erreur s’est produite. Veuillez réessayer.",
    dark: "🌙 Sombre",
    light: "☀️ Clair",
    footer: "Cross-Cultural Translator™",
    audience: "À qui parlez-vous ?",
    tone: "Ton / intention",
    goal: "Type de situation",
    contextMode: "Mode de communication",
    situation: "Contexte supplémentaire (facultatif)",
    situationPlaceholder: "Exemple : message à un ami, réception d’hôtel, message romantique, courriel professionnel...",
    includeInfo: "Afficher les notes culturelles / de ton quand elles sont utiles",
    simpleMode: "Simple",
    enhancedMode: "Contexte avancé",
    pronunciationToggleLabel: "Afficher la prononciation",
    pronunciation: "Prononciation",
    speakNormal: "Parler normalement",
    speakSlow: "Parler lentement",
    typeMoreToDetect: "Tapez un peu plus pour détecter la langue",
    unsupportedPronunciation: "La prononciation n’est pas encore disponible pour cette paire de langues.",
    audienceOptions: {
      general: "Général",
      friend: "Ami(e)",
      romantic: "Intérêt romantique",
      professional: "Professionnel / supérieur",
      stranger: "Inconnu(e)",
      service: "Employé(e) de service"
    },
    toneOptions: {
      natural: "Naturel et clair",
      casual: "Décontracté",
      formal: "Formel",
      respectful: "Respectueux",
      playful: "Enjoué",
      urgent: "Urgent / direct"
    },
    goalOptions: {
      translate: "Traduction générale",
      travel: "Voyage / logistique",
      business: "Affaires / professionnel",
      social: "Message social",
      conflict: "Conflit / tension",
      flirting: "Flirt / alchimie"
    },
    contextModeOptions: {
      normal: "Normal",
      romantic: "Romantique / flirt",
      fictionalDialogue: "Dialogue fictif / roman",
      professional: "Professionnel",
      conflict: "Conflit / escalade"
    }
  },

  de: {
    siteLanguage: "Seitensprache",
    title: "Cross-Cultural Translator™",
    subtitle: "Mehr als Übersetzung — echte interkulturelle Kommunikation",
    description: "Dialektbewusste Übersetzung und kulturelle Klarheit",
    inputText: "Eingabetext",
    detected: "Erkannte Sprache",
    confirmed: "Eingabesprache",
    keep: "Behalten",
    change: "Ändern",
    changeInput: "Eingabesprache ändern zu:",
    translateTo: "Übersetzen in",
    translate: "Übersetzen",
    translating: "Übersetzt...",
    translation: "Übersetzung",
    copy: "Kopieren",
    copied: "Kopiert",
    additionalInfo: "Zusätzliche Informationen",
    confirmInputFirst: "Bitte zuerst die Eingabesprache bestätigen",
    enterTextTarget: "Text eingeben und eine Sprache wählen",
    genericError: "Etwas ist schiefgelaufen. Bitte versuchen Sie es erneut.",
    dark: "🌙 Dunkel",
    light: "☀️ Hell",
    footer: "Cross-Cultural Translator™",
    audience: "Mit wem sprechen Sie?",
    tone: "Ton / Absicht",
    goal: "Art der Situation",
    contextMode: "Kommunikationsmodus",
    situation: "Zusätzlicher Kontext (optional)",
    situationPlaceholder: "Beispiel: Nachricht an einen Freund, Hotelrezeption, romantische Nachricht, geschäftliche E-Mail...",
    includeInfo: "Kultur- / Tonhinweise anzeigen, wenn hilfreich",
    simpleMode: "Einfach",
    enhancedMode: "Erweiterter Kontext",
    pronunciationToggleLabel: "Aussprache anzeigen",
    pronunciation: "Aussprache",
    speakNormal: "Normal sprechen",
    speakSlow: "Langsam sprechen",
    typeMoreToDetect: "Geben Sie etwas mehr Text ein, um die Sprache zu erkennen",
    unsupportedPronunciation: "Aussprache ist für dieses Sprachpaar noch nicht verfügbar.",
    audienceOptions: {
      general: "Allgemein",
      friend: "Freund/in",
      romantic: "Romantisches Interesse",
      professional: "Beruflich / Chef/in",
      stranger: "Fremde Person",
      service: "Service-Mitarbeiter/in"
    },
    toneOptions: {
      natural: "Natürlich und klar",
      casual: "Locker",
      formal: "Formell",
      respectful: "Respektvoll",
      playful: "Verspielt",
      urgent: "Dringend / direkt"
    },
    goalOptions: {
      translate: "Allgemeine Übersetzung",
      travel: "Reise / Logistik",
      business: "Geschäftlich / professionell",
      social: "Soziale Nachricht",
      conflict: "Konflikt / Spannung",
      flirting: "Flirt / Chemie"
    },
    contextModeOptions: {
      normal: "Normal",
      romantic: "Romantisch / flirtend",
      fictionalDialogue: "Fiktiver Dialog / Roman",
      professional: "Professionell",
      conflict: "Konflikt / Eskalation"
    }
  },

  "pt-BR": {
    siteLanguage: "Idioma do site",
    title: "Cross-Cultural Translator™",
    subtitle: "Além da tradução — comunicação intercultural de verdade",
    description: "Tradução sensível a dialetos e clareza cultural",
    inputText: "Texto de entrada",
    detected: "Idioma detectado",
    confirmed: "Idioma de entrada",
    keep: "Manter",
    change: "Alterar",
    changeInput: "Alterar idioma de entrada para:",
    translateTo: "Traduzir para",
    translate: "Traduzir",
    translating: "Traduzindo...",
    translation: "Tradução",
    copy: "Copiar",
    copied: "Copiado",
    additionalInfo: "Informações adicionais",
    confirmInputFirst: "Confirme primeiro o idioma de entrada",
    enterTextTarget: "Digite o texto e escolha um idioma",
    genericError: "Algo deu errado. Tente novamente.",
    dark: "🌙 Escuro",
    light: "☀️ Claro",
    footer: "Cross-Cultural Translator™",
    audience: "Com quem você está falando?",
    tone: "Tom / intenção",
    goal: "Tipo de situação",
    contextMode: "Modo de comunicação",
    situation: "Contexto extra (opcional)",
    situationPlaceholder: "Exemplo: mensagem para um amigo, recepção de hotel, mensagem romântica, e-mail de trabalho...",
    includeInfo: "Mostrar notas culturais / de tom quando forem úteis",
    simpleMode: "Simples",
    enhancedMode: "Contexto avançado",
    pronunciationToggleLabel: "Mostrar pronúncia",
    pronunciation: "Pronúncia",
    speakNormal: "Falar normalmente",
    speakSlow: "Falar devagar",
    typeMoreToDetect: "Digite um pouco mais para detectar o idioma",
    unsupportedPronunciation: "A pronúncia ainda não está disponível para este par de idiomas.",
    audienceOptions: {
      general: "Geral",
      friend: "Amigo(a)",
      romantic: "Interesse romântico",
      professional: "Profissional / chefe",
      stranger: "Desconhecido(a)",
      service: "Funcionário(a) de atendimento"
    },
    toneOptions: {
      natural: "Natural e claro",
      casual: "Casual",
      formal: "Formal",
      respectful: "Respeitoso",
      playful: "Brincalhão",
      urgent: "Urgente / direto"
    },
    goalOptions: {
      translate: "Tradução geral",
      travel: "Viagem / logística",
      business: "Negócios / profissional",
      social: "Mensagem social",
      conflict: "Conflito / tensão",
      flirting: "Flertar / química"
    },
    contextModeOptions: {
      normal: "Normal",
      romantic: "Romântico / paquera",
      fictionalDialogue: "Diálogo fictício / romance",
      professional: "Profissional",
      conflict: "Conflito / escalada"
    }
  }
};
